# Use this to find available exception rules:
#   rubocop --auto-gen-config

Metrics/LineLength:
  Max: 120

Metrics/ParameterLists:
  Max: 8

Metrics/ModuleLength:
  Max: 115

Metrics/ClassLength:
  Max: 100

Metrics/MethodLength:
  Max: 30

Metrics/AbcSize:
  Max: 55

Metrics/PerceivedComplexity:
  Max: 20

Metrics/CyclomaticComplexity:
  Max: 15
